const actionTypes = {
    LOAD_USER_READ : 'LOAD_USER_READ',
    LOAD_USER_WANT_TO_READ : 'LOAD_USER_WANT_TO_READ',
    LOAD_USER_CURRENTLY_READING : 'LOAD_USER_CURRENTLY_READING',
    LOAD_USER_PROFILE : 'LOAD_USER_PROFILE',
    UPDATE_USER_PROFILE : 'UPDATE_USER_PROFILE',
    LOAD_TRENDING_POSTS : 'LOAD_TRENDING_POSTS',
    LOAD_POPULAR_POSTS : 'LOAD_POPULAR_POSTS',
    LOAD_NEW_POSTS : 'LOAD_NEW_POSTS',
    LOAD_ALL_BOOKS : 'LOAD_ALL_BOOKS',
    LOAD_ALL_MAGAZINES : 'LOAD_ALL_MAGAZINES',
    LOAD_ALL_ARTICLES : 'LOAD_ALL_ARTICLES',
    LOAD_BOOKS_BY_CATEGORY : 'LOAD_BOOKS_BY_CATEGORY',
    LOAD_MAGAZINES_BY_CATEGORY : 'LOAD_MAGAZINES_BY_CATEGORY',
    LOAD_ARTICLES_BY_CATEGORY : 'LOAD_ARTICLES_BY_CATEGORY',
    LOAD_BOOK_DETAILS : 'LOAD_BOOK_DETAILS',
    LOAD_MAGAZINE_DETAILS : 'LOAD_MAGAZINE_DETAILS',
    LOAD_ARTICLE_DETAILS : 'LOAD_ARTICLE_DETAILS',
    LOAD_BOOK_CATEGORIES : 'LOAD_BOOK_CATEGORIES',
    LOAD_MAGAZINE_CATEGORIES : 'LOAD_MAGAZINE_CATEGORIES',
    LOAD_ARTICLE_CATEGORIES : 'LOAD_ARTICLE_CATEGORIES',
};

export default actionTypes;