const actionTypes = {
    LOAD_USER_READ : 'LOAD_USER_READ',
    LOAD_USER_WANT_TO_READ : 'LOAD_USER_WANT_TO_READ',
    LOAD_USER_CURRENTLY_READING : 'LOAD_USER_CURRENTLY_READING'
};

export default actionTypes;